- README.md
- android/src/main/java/it/innove/BleManager.java
- android/src/main/java/it/innove/BleManagerPackage.java
The new version of react native seems to change Android application templates which breaks this module. According to the release notes:
"Plugins which pass activity reference in the constructor need to be updated to extend ReactContextBaseJavaModule use getCurrentActivity to get the activity reference. This change is backward compatible."
> Update to work with react-native v0.29 (Android)

- android/src/main/java/it/innove/BleManager.java
- android/src/main/java/it/innove/Peripheral.java
- ios/BleManager.h
- ios/BleManager.m
* 3 methods were added:
```js
//Stop scan
BleManager.stopScan(function([Error], [Array]))
//Get already discovered peripherals
BleManager.getDiscoveredPeripherals(function([Error], [Array]))
//Get connected peripherals
BleManager.getConnectedPeripherals(function([Error], [Array]))
```
* Use `gatt.disconnect()` instead `gatt.close()`.
Closing gatt will force use to restart ble adaptater.
* Do not close gatt after a disconnect
* Add a `writeErrorCallbacks` property to handle correct error on write with response like UNLIKELY ERROR
> [iOS +  Android] Add methods to get discovered peripherals,  get connected peripherals, stop scan + somes fixes

- android/src/main/java/it/innove/BleManager.java
- android/src/main/java/it/innove/Peripheral.java
- ios/BleManager.m
- ios/BleManager.xcodeproj/project.pbxproj
Sorry, i forget to register the error callback in the write method, I also modify the getConnectedPeripherals to return only peripherals that are connected with the system.
It takes a new argument ServiceUUids
> [iOS] Fix forget to register writeErrorCallback + better getConnectedPeripherals on system only

- BleManager.js
- README.md
- android/src/main/java/it/innove/BleManager.java
- android/src/main/java/it/innove/Peripheral.java
- ios/BleManager.m
I am working with a BLE device that requires a single message packet of > 20 bytes (23 in my case). I made these changes to allow the default max byte size for messages to be overridden if desired. The default is still `20`.
Before these changes the `react-native-ble-manager` library was incompatible with this device. After these changes, it is now fully compatible.
Would greatly appreciate feedback on this. And would hope to have the library support this functionality.
> [iOS + Android] Add max byte size param to write method

- android/src/main/java/it/innove/BleManager.java
Removing `successCallback.invoke()` and data size check as they are already done inside peripheral's `write`.
Fixes https://github.com/innoveit/react-native-ble-manager/issues/40
> Remove redundant callback in writeWithoutResponse

- BleManager.js
- android/src/main/java/it/innove/BleManager.java
- ios/BleManager.m
These methods were not working for me. They were seeming to return 2 element arrays with `null` as the first item, then checking if `result[0] != null` (which would always be false), triggering `fulfill(result[1])` (which could be null if no peripherals were found).
With the code as-is I kept getting the following error on iOS and Android: `null is not an object (evaluating 'result[0]')` on `BleManager.js:113`. It seems that `result` itself was being set to null and therefore `result[0]` was failing.
The following changes cause things to work correctly for me in iOS/Android. I also changed it so it simply returns an empty array if no devices are found, rather than a promise rejection.
@Rmannn please chime in if I'm missing something or way off base here.
> [iOS + Android] Fix getConnectedPeripherals and getDiscoveredPeripherals

- BleManager.js
- ios/BleManager.m
Was getting "mutated while being enumerated" error because `peripherals` was being updated during discovery while I was attempting to read `getDiscoveredPeripherals`. This locks it while it's being looped through.
Also was running into a context issue in `isPeripheralConnected`. Fixed that as well.
> Fix context issue with isPeripheralConnected and make getDiscoveredPeripherals thread-safe

- ios/BleManager.m
I get an error when these failCallbacks are triggered because they are also being passed to `BLECommandContext` which is triggering them upon certain conditions. `nil` is returned when there is an error and then they are triggered for a second time in the `write` functions. Removing them seems to fix the issues without any adverse side effects.
> Fix multiple failCallbacks being triggered

- android/src/main/java/it/innove/BleManager.java
This fixes invalid or null peripheral id.
The method checkBluetoothAddress actually validates the address if it is uppercase.
If the address is null or not a valid bluetooth address, the callback is called with an error.
Feel free to edit the error message or anything you want
> Check the peripheral id is valid before creating a Bluetooth Device in the android connect method

- ios/BleManager.m
writeCallback not called for long data, cause already removed from list.
> Callback not called long data

- android/src/main/java/it/innove/BleManager.java
After connecting to a BT-device on Android, an error occured which said, that serviceUUID was null.
This fork fixes that issue.
> getConnectedPeripherals: check for null

- ios/BleManager.h
- ios/BleManager.m
Invalidate NSTimer created to stop scanning of scanForPeripheralsWithServices.
This will prevent 'unexpected' [manager stopScan] when manual stopScan called before scan timeout.
> iOS: Stop NSTimer on manual stopScan

- android/src/main/java/it/innove/BleManager.java
request code 1 is very commonly used as the default, and so there is a high chance for conflicts that can take quite a while to debug (I had a conflict with react-native-android-location-services-dialog-box). It's best to choose a number that's a bit more random.
> changed activity request code

- android/src/main/java/it/innove/BleManager.java
- android/src/main/java/it/innove/BleManagerPackage.java
- android/src/main/java/it/innove/Peripheral.java
- preventing crash when user disables bluetooth before scan is stopped (see commit message)
- preventing NullPointerException in write() method in Peripheral.java
- cleaned up some code
> stopping scan only if bt adapter is still ON / NullPointerException fix in Peripheral / cleanup

- BleManager.js
- README.md
- android/src/main/java/it/innove/BleManager.java
Sort of a fix for #126 
Allows the user to manually remove a disconnected device from the 'peripherals', so a new event is fired for it after the device is re-discovered.
It is useful for my scenario, in which devices timeout and turn themselves off and on and I need to reconnect to them each time.
> Added a removePeripheral method to delete a cached peripheral from the list

- README.md
Hi, just adapting this library to my next project and really appreciate for it!
regarding issue 115 (https://github.com/innoveit/react-native-ble-manager/issues/115):
I have tested the result for using `react-native link` to link native modules for both platforms:
* iOS: work properly
* Android: still need to update `build.gradle` about `minSdkVersion`
I haven't found an easy way to directly changing `minSkdVersion`, but I think using `react-native link` is still much easier than manual linking.
> Update README.md about how to link native module

- README.md
- ios/BleManager.m
This PR adds basic support for CoreBluetooth state restoration on iOS.
I've created an example project that successfully uses this functionality that may be found [here](https://github.com/Looveh/ble-state-restoration).
> CoreBluetooth state restoration

- android/src/main/java/it/innove/BleManager.java
Scanning while calling `getDiscoveredPeripherals` / `getConnectedPeripherals` can cause a `concurrentModificationException` if the `peripherals` map is simultaneously being iterated in a for loop and items are removed from it in the `scan` method.
Making a copy of the map in these methods prevents this behavior.
> Make copy of peripherals hashmap to prevent exception while scanning

- ios/BleManager.m
- ios/CBPeripheral+Extensions.m
Fix issue #183 
Apple has deprecated following APIs from iOS 8:
* `peripheralDidUpdateRSSI:error:` from `CBPeripheralDelegate` (https://developer.apple.com/documentation/corebluetooth/cbperipheraldelegate/1519083-peripheraldidupdaterssi?language=objc)
* `RSSI` from `CBPeripheral` (https://developer.apple.com/documentation/corebluetooth/cbperipheral/1518869-rssi?language=objc)
Since this library is also targeting iOS 8+, it should be safe to remove them.
> Remove deprecated rssi usage for iOS

- android/src/main/java/it/innove/BleManagerPackage.java
Related to issue #195 , this is because of the breaking change for RN47:
* https://github.com/facebook/react-native/commit/ce6fb337a146e6f261f2afb564aa19363774a7a8
Thanks!
> Breaking change for RN47: remove deprecated createJSModules @Override

- BleManager.js
- README.md
- android/src/main/java/it/innove/BleManager.java
Export `getBondedPeripherals` API for Android, which maps to native API `getBondedDevices`
* https://developer.android.com/reference/android/bluetooth/BluetoothAdapter.html#getBondedDevices()
Tested in Android 6 / 7, and also updated the README.
Currently there's no good solution to retrieve bonded list in iOS, so it's an Android only API for now.
> Export `getBondedPeripherals` API for Android

- ios/BleManager.h
- ios/BleManager.m
This is necessary for advanced integration with external libraries on iOS when the delegate of the manager is changed temporarily.
> Expose the BleManager instance created by RN

- ios/BleManager.m
I noticed that the connect callback is never called on iOS when you receive a delegate call to `didFailToConnectPeripheral`, this fixes that and conforms the iOS and Android APIs.
> Reject the connect callback when connect fails on ios

- BleManager.js
- README.md
- android/src/main/java/it/innove/BleManager.java
This patch contains three changes:
1. expose `createBond` API
2. extract `retrieveOrCreatePeripheral` as an utility method, which is required by both `createBond` and `connect`
3. register broadcast receiver to capture bond state change.
Thanks!
> Export createBond API for Android

- ios/BleManager.m
This PR fixes inconsistencies in how pending promises were never rejected if a peripheral disconnected before a bluetooth operation was completed, making it difficult to reason about program flow and handle sequential bluetooth operations.
Example:
1. Connect to peripheral successfully
2. Call `retrieveServices`
3. Peripheral disconnects
4. The promise returned by `retrieveServices` is never resolved/rejected
This PR rejects all pending promises and removes references to them when a peripheral is disconnected, as well as fixing a few bugs where the promises were never removed in the first place after being resolved.
> Reject and remove pending promises when disconnected

- .npmignore
- android/src/main/java/it/innove/LollipopScanManager.java
- android/src/main/java/it/innove/Peripheral.java
- Reject the promises when the device disconnects (same thing as: https://github.com/innoveit/react-native-ble-manager/pull/220, but for Android) 
- It will assure that one is connected before attempting to run any methods requiring a connected device
- Ignore the `example` folder from being published to npm
> [Android] Reject callbacks when disconnecting and assure connection before attempting some methods

- README.md
- example/App.js
Remove the extra dependencies in `example/App.js`, let it only depends on RN itself. Thus the example project can be easily setup by directly point the `AppRegistry` to this file, like this:
```javascript
import React, { Component } from 'react';
import {
AppRegistry,
} from 'react-native';
import App from 'react-native-ble-manager/example/App' //<-- simply point to the example js! 
AppRegistry.registerComponent('MyAwesomeApp', () => App);
```
The `README` is also updated.
> Remove the unnecessary dep in example/App.js, allow easier testing and

- ios/BleManager.m
Calling toArray leads exception for empty characteristic values (backed by _NSZeroData). Such exception cause app crash:
---
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[1]'
---
To prevent exception, check the value and pass NSNull as result for empty ones.
> Handle reading of empty value.

- README.md
Explain the iOS connect API won't timeout itself, as discussed in issue #249
> Update README to describe iOS connect behavior

- ios/BleManager.m
Bug logs:
2018-05-09 17:29:54.809 [fatal][tid:com.facebook.react.BleManagerQueue] Exception '*** Collection <__NSSetM: 0x121e92e60> was mutated while being enumerated.' was thrown while invoking getDiscoveredPeripherals on target BleManager with params (
14229
)
callstack: (
0   CoreFoundation                      0x0000000181ee2da4 <redacted> + 252
1   libobjc.A.dylib                     0x000000018109c5ec objc_exception_throw + 56
2   CoreFoundation                      0x0000000181ee23c0 <redacted> + 0
3   KfRn                                0x0000000100c5f05c -[BleManager getDiscoveredPeripherals:] + 364
4   CoreFoundation                      0x0000000181eea580 <redacted> + 144
5   CoreFoundation                      0x0000000181dc9748 <redacted> + 284
6   CoreFoundation …
> Fix peripherals was mutated while being enumerated (30+ peripheral)

- android/src/main/java/it/innove/BleManager.java
Android report "Bluetooth not enabled" error, but iOS didn't, this will cause 'Possible Unhandled Promise Rejection' in react-native.
> remove error when bluetooth disabled in stopScan.

- android/src/main/java/it/innove/LollipopScanManager.java
- android/src/main/java/it/innove/Peripheral.java
- ios/BleManager.xcodeproj/project.pbxproj
- ios/BleManager.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- ios/CBPeripheral+Extensions.m
I unified the advertising data object, so the "advertising" object in a scan result should look pretty much the same between iOS and Android.
Especially nice since the Android part was quite lacking in this regard.
You can test the changes by scanning for BLE devices around you and comparing the scan result, or I can add examples later if needed.
> Better advertising data (iOS and Android)

- android/src/main/java/it/innove/Peripheral.java
#338 introduced a change to Peripheral.retrieveServices(callback) so that callback is callback is always invoked instead of letting gatt.discoverServices() invoke the callback as it was until now.
this results in the BleMananger.retrieveServices(id) to always resolve to null.
> BleManager.retrieveServices(id) always returns null

- android/src/main/java/it/innove/Peripheral.java
Make Android in version higher than Lollipop take localName from advertising record as in IOS. When it's not there localName is same as name in Android so we don't even need that field.
Fix in Android > Lollipop take advertisingData from scanRecord when new peripheral found. Then in react native we can see advertising -> services and advertising-> localName
> Make Android > Lollipop use name from advertising record as localName

- ios/CBPeripheral+Extensions.m
I experienced a crash on iOS 11.4 in `dataToArrayBuffer` when connecting to a BLE peripheral. This peripheral has a characteristic with value 0x (byte array of length 0).
When `data` is empty, `[data toArray]` returns nil and causes a crash. See error below.
`*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[2]'`
This fixes the problem for me. Alternatively, `dataToArrayBuffer` can updated to support empty data. If someone knows NSData well, this could be another solution.
> Fix: The app crashes when a characteristic with 0x value is discovered

- android/src/main/java/it/innove/Peripheral.java
There are lots of NullPointerExceptions in getDeviceName in versions above LolliPop some of the advertisement return Null in getDeviceName, subsequent replace is causing NullPointer exception. 
Adding checks to avoid NullPointerException
> Fixing NullPointerException in getDeviceName

- BleManager.js
- README.md
- android/src/main/java/it/innove/BleManager.java
- ios/BleManager.m
Hi there,
Thanks for the excellent library!  This PR adds iOS only support for selective service discovery/retrieval by simply passing the optional `services` parameter through to [[discoverServices:serviceUUIDs?]](https://developer.apple.com/documentation/corebluetooth/cbperipheral/1518706-discoverservices). 
Utilizing this parameter can lead to a dramatic reduction in time between initiating a connection and reading or writing a known characteristic.  Mileage will vary by GATT table, in our very specific case this reduced times from about ~3s to ~0.5s.
I'm not the best native android dev, but as far as I can tell this isn't supported by [BluetoothGATT](https://developer.android.com/reference/android/bluetooth/BluetoothGatt.html#discoverServices()) on Android.  Happy to be proved wrong …
> Selective service retrieval

- ios/BleManager.m
synchronizing peripherals so that they are mutated while iterating peripherals
For example by the callbacks such as getDiscoveredPeripherals
> Synchronizing the peripherals before iterating

- README.md
- android/src/main/java/it/innove/BleManager.java
After #398 , `retrieveServices` seems not working at all on Android. 
Following code is introduced in that p-r:
```java
@ReactMethod
public void retrieveServices(String deviceUUID, String[] services, Callback callback) {
```
`String[]` here must be `ReadableArray`, otherwise compile will success but will not work with runtime error. 
This p-r just fix it. I hope this will be released soon.
> Fix retrieveServices on Android

- android/src/main/java/it/innove/BleManager.java
- android/src/main/java/it/innove/LegacyScanManager.java
- android/src/main/java/it/innove/LollipopScanManager.java
- android/src/main/java/it/innove/Peripheral.java
The goal was to be able to use or disconnect from an already connected BLE device after an app restart/reload (without scanning) on Android. Previously these always resulted in a "Peripheral not found" error.
- Changed the map's visibility to private and moved Peripheral creation logic inside BleManager to make it cleaner. And used this savePeripheral method inside getConnectedPeripherals. 
- Added synchronized blocks for every modification of the map. These might not be necessary but a LinkedHashMap does not guarantee thread safety.
- Other changes are auto-formatting and import related.
These related issues may get fixed: #276  and #318
> Fill the internal peripherals map in the getConnectedPeripherals method

- android/src/main/java/it/innove/Peripheral.java
According to the documentation of BluetoothGattCallback
In onConnectionStateChange, newState Can be one of
BluetoothProfile.STATE_DISCONNECTED or
BluetoothProfile.STATE_CONNECTED
> Using correct constants for newState in onConnectionStateChange

- BleManager.js
- README.md
- android/src/main/java/it/innove/BleManager.java
- android/src/main/java/it/innove/Peripheral.java
- index.d.ts
- ios/BleManager.m
- package.json
Reason gatt.disconnect would trigger an
onConnectionStateChange, but an immediate
gatt.close would unregisterApp would remove
all the needed resources notify the BluetoothGattCallback
object.
In short there is no need of calling disconnect if close
is being called immediately
Check https://stackoverflow.com/questions/23110295/difference-between-close-and-disconnect
Also check the below stackTrace - leading to an exception which could be avoided
```
D/BluetoothLeScanner: onClientRegistered() - status=0 clientIf=5 mClientIf=0
D/ReactNativeBleManager: Disconnect from: 00:0E:0B:15:AC:98
D/BluetoothGatt: cancelOpen() - device: 00:0E:0B:15:AC:XX
D/BluetoothGatt: close()
D/BluetoothGatt: onClientConnectionState() - status=0 clientIf=11 device=00:0E:0B:15:AC:XX
D/BluetoothGatt: unregisterApp() - …
```
> Removing gatt.disconnect in the disconnect

- android/src/main/java/it/innove/BleManager.java
- android/src/main/java/it/innove/Peripheral.java
If a device was already connected when we turned off the Bluetooth adapter it caused an inconsistent state on Android: the Peripheral object's **connected flag stayed true**. And the following connect() calls would return a false positive.
Removing all items from the internal map when the state changed to "off" seems to be the simplest solution. 
Trying to do a graceful disconnect on "turning_off" is just an extra attempt to handle states according to the Android Api's documentation.
possibly related issue: #366
> Clear invalid data on adapter state change (Andorid)

- ios/BleManager.m
Tell us which versions you are using:
- react-native-ble-manager v6.62
- react-native v0.59 SDK 32
- iOS/Android iOS v.12
When scanning for devices it shows up correctly.  Calling disconnect and rescan the devices again.  And then attempt to try to connect any new devices or the same device will NOT allow you to connect.
Should clear the peripherals cache before scanning again. 
1.  Scan -> Connect
2. Disconnect from that Device
3. Rescan again, cannot connect again
> Scanning on iOS does not clear peripherals cache in order to connect to same devices or other devices already previously scanned

- android/src/main/java/it/innove/BleManager.java
Call sendEvent in BroadcastReceiver to broadcast a successful bond in case createBond is never called and some other bluetooth functionality calls it.
> The BOND_BONDED state event callback is not called #493

- android/src/main/AndroidManifest.xml
App does not require ble to be supported, hence app should be allowed to be installed through play store
> ble support is optional

- ios/BleManager.m
Connecting to peripheral was working on the first scan, and sometimes on subsequent scans after the fix in 6.6.4. However, there were still issues connecting to peripherals with the following message:
API MISUSE: Cancelling connection for unused peripheral <CBPeripheralXXXX>, Did you forget to keep a reference to it?
Keeping the connecting/connected peripherals across scans appears to resolve the issue.
> Updated peripheral list to not clear connecting/connected peripherals

- android/src/main/java/it/innove/BleManager.java
With this change, the devices with does not support BLUETOOH_LE will return state as unsupported instead of "off", which happens currently
> Fixing unsupported state in android

- android/src/main/java/it/innove/BleManager.java
stop function execution after callback invocation, otherwise the code falls through to another callback and app crashes with error `Illegal callback invocation from native module. The callback type only permits a single invocation from native code`
> Fix multiple callback invocation

- README.md
- ios/BleManager.m
Previously, the main queue was passed to the initializer or `CBCentralManager`. It means the BLE events happened always in the main thread and were handled there. It had risks to block the UI.
With this fix, we can use a background thread by passing a queue identifier on which the events will be dispatched as follows:
```
BleManager.start({showAlert: false, queueIdentifierKey: 'com.shu223.example.queue.centralmanager'})
```
> Enable to pass a queue identifier on which the events will be dispatched

- index.d.ts
As documented at https://github.com/innoveit/react-native-ble-manager#startoptions
> [TS] Add queueIdentifierKey to start()

- ios/CBPeripheral+Extensions.m
Raising this as there are times when nil service data is captured from external Bluetooth devices during a scan and hence cause a crash.
> Fixed nil service data when broadcast by device

- android/src/main/java/it/innove/BleManager.java
A copy of peripherals map was added to address this same exception, in a previous PR, but exception can still occur
Exception occurs if copy is being made of `peripherals` while `scan` is modifying `peripherals`
This PR adds a synchronized block in getDiscoveredPeripherals, following the convention in the rest of the code, and removes the copy
> Add synchronized to Android getDiscoveredPeripherals to fix ConcurrentModificationException

- README.md
- ios/BleManager.m
Hi, 
When iOS app is relaunched to handle a bluetooth event, we should be able to handle that from JS code too.
I added an additional event for that.
> Handle central manager state restoration on iOS

- index.d.ts
The return types of the get functions should not be `any` or `void`. Instead use the correct `Peripheral` interface
> fix: typescript return types to be a peripheral

- ios/NSData+Conversion.m
For some devices on iOS, when advertisement data is parsed with `serializableAdvertisementData`, the service data (value for `CBAdvertisementDataServiceDataKey`) might be `NULL`, which causes `(NSArray *)toArray` to return `NULL` and it raises `NSInvalidArgumentException` exception when we try to put this `NULL` as a value to `NSPlaceholderDictionary`.
To fix it I return empty array instead of `NULL` in from `(NSArray *)toArray` function.
It might fix the following issue:
https://github.com/innoveit/react-native-ble-manager/issues/542
> Fix NSInvalidArgumentException on iOS when parsing advertisement data for some devices

- android/src/main/java/it/innove/Peripheral.java
- ios/BleManager.m
This is a fix to prevent fast reconnection attempts to eat up all available BLE identifiers.
> Android gatt close fix

- android/src/main/java/it/innove/LollipopScanManager.java
with using 7.1.0. If you did not send the ScanOption, you would get an error below
Just as the type definition of scan method
https://github.com/innoveit/react-native-ble-manager/blob/08aa0475349bc76e0f0c9f86232c24565e3c5094/index.d.ts#L34
the ScanOption in method scan is an option parameter, so we should check the option before using it
> Add scanOption check

- ios/BleManager.m
Here is a quick patch that helps when trying to reconnect in the background. The serial dispatch policy was not enough to have it working for me on iOS 13. I had to add the QOS_CLASS_BACKGROUND attribute to the dispatch queue.
> use QOS_CLASS_BACKGROUND for the background dispatch queue

- README.md
With Android API 29 Android did some changes to their permission system.
https://developer.android.com/about/versions/10/privacy/changes
"If your app targets Android 10 or higher, it must have the ACCESS_FINE_LOCATION permission in order to use several methods within the Wi-Fi, Wi-Fi Aware, or Bluetooth APIs. The following sections list the affected classes and methods."
> add Android 10 permission handling to docs

- index.d.ts
param peripheralPin of createBond function should be typed as optional.
> param peripheralPin of createBond should be typed as optional

- ios/BleManager.m
Bug. Division of integer results in setting sleep time zero with lost packages as a consequence.
> Bugfix; sleep time always zero

- example/App.js
Fix for error:
`TypeError: bleManagerEmitter.removeEventListener is not a function. (In 'bleManagerEmitter.removeEventListener('BleManagerDiscoverPeripheral', handleDiscoverPeripheral)', 'bleManagerEmitter.removeEventListener' is undefined)`
> Change removeEventListener to removeListener

- react-native-ble-manager.podspec
Latest Xcode 12 fails to build while without a module to depend on `React-Core` directly hence this change is necessary for all native modules on iOS. For more details please check: [facebook/react-native#29633 (comment)](https://github.com/facebook/react-native/issues/29633#issuecomment-694187116)
> fix: Xcode 12 compatibility

- ios/BleManager.m
for some peripheral there is a possibility that characteristics are part of a service where the service it self is actually an included service.
discovering this type of characteristic requires implementation of [discoverIncludedServices:forService:
](https://developer.apple.com/documentation/corebluetooth/cbperipheral/1519014-discoverincludedservices?language=objc)
> add discover characteristics in included service (ios)

- ios/NSData+Conversion.m
- package.json
Backports https://github.com/innoveit/react-native-ble-manager/pull/624 to v6.
@marcosinigaglia Thanks for all your work on the library! Would it be possible to release a v6.7.2 patch from this branch? All the PR does is backport the fix to the v6 version of the lib
> backport NSInvalidArgumentException fix to v6

- android/src/main/java/it/innove/BleManager.java
- package.json
This will suppress the warnings shown by React v0.65.
WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `addListener` method.
WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `removeListeners` method.
> Fix for RN event warnings

- android/src/main/java/it/innove/Peripheral.java
The "sendConnectionEvent()" method was duplicate when "disconnect()" method is trigger on Peripheral.java file.
> fix: remove duplicate disconnect event trigger

- android/src/main/java/it/innove/Peripheral.java
Issue:
On Android, the connect promise will be held on connection fail. It won't fulfil nor reject.
Recreate issue:
BleManager.connect(peripheral).then(function(){
console.log("Connection success");
}).catch(function(error){
console.log("Connection Fail, but this line will never run");
})
Cause:
in the onConnectionStateChange function under Peripheral.java, when the state changed to STATE_DISCONNECTED, it will immediate trigger disconnect. But disconnect function will remove the connection callback, which render the promise rejection on the next few line unusable.
Fix:
Move the disconnect function call after all the callback reset and queue clear.
> Fix connect promise will never reject on error

- android/src/main/java/it/innove/BleManager.java
- android/src/main/java/it/innove/Peripheral.java
Issue:
On Android, if we try to repeating scanning for BLE device and try to repeat connect to a device through MAC address at the same time, we will experience "Peripheral Not Found" on retrieveServices after device connected.
Recreate issue:
var BleManagerModule = NativeModules.BleManager;
var ble_emitter = new NativeEventEmitter(BleManagerModule);
const onConnect = function ({ peripheral }) {
BleManager.retrieveServices(peripheral).then(function () {
console.log("Connection Successful");
//Further Action
}).catch(function (error) {
console.log("Retrieve Servcies Error:", error);
//Peripheral Not Found
});
}
const onDisconnect = function ({ peripheral }) {
BleManager.connect(peripheral).catch(function () {
console.log("Reconnection Fail ", peripheral);
});
}
const onScanStop = function …
> Fix "peripheral not found" on retrieveServices while scanning [Android]

- README.md
- ios/BleManager.m
Implements #798. Solved by just adding a `domain` and a `code` field to the `BleManagerDisconnetPeripheral` event. Similar to how the solution is with the android `status`.
> Add NSError domain and NSError code to BleManagerDisconnectPeripheral event

- README.md
- ios/BleManager.m
Adding a new event listener to listen for `didUpdateNotificationStateFor` events. https://developer.apple.com/documentation/corebluetooth/cbperipheraldelegate/1518768-peripheral
My use case is to be able to detect for failed bonds by listening for this event https://developer.apple.com/documentation/corebluetooth/cbatterror/code/insufficientencryption
I suspect there are a lot of other use cases for this too, so prolly nice to include.
I have run my tests on a iPhone 8. It is tested manually with a few different peripherals I have available.
> Add BleManagerDidUpdateNotificationStateFor

- android/src/main/java/it/innove/LollipopScanManager.java
- index.d.ts
Hello, 
there is an option in the android ScanSettingsBuilder to use newer features introduced in bluetooth 5. The name of this option is [setLegacy](https://developer.android.com/reference/android/bluetooth/le/ScanSettings.Builder#setLegacy(boolean)), and it allows for features such as BLE extended broadcasting. By default, the value is true, but having the option to set it to false would be a good feature to have. I have tested with a sample app, and it does pick up on BLE extended broadcasting.
> added setLegacy option to scan method

- android/src/main/java/it/innove/Peripheral.java
Previously the `onReadRemoteRssi` callback did not call `completedCommand`, which appears to be necessary to unlock the `commandQueue`.
Additionally the readRSSI previously nulled the `readCallback` which does not appear to be correct, as that callback belongs to a read operation. Instead, it should null its own callback field: `readRSSICallback`
This fixes #876 for me. It is worth noting that the example app does readRSSI after connecting to a device, so this issue might be fairly common.
> Fix readRSSI locking up the commandQueue on android

- android/src/main/java/it/innove/Peripheral.java
Prior to this patch, on abrupt disconnection while reading, there was an React Native MessageQueue exception
> Fix to avoid MessageQueue Invariant Violation

- README.md
To avoid that other people run into a similar problem in the past, I've updated the documentation to include the default maxByteSize of the write function.
> Updated README.md to include default maxByteSize of write function

- android/src/main/java/it/innove/Peripheral.java
This change fixes two possible null pointer exceptions that result from passing a null reference to `sendBackrError` which invokes the passed callback without performing a null check.
- Peripheral.java line 835 `writeCallback` can be set to null if a write without response is performed.
- If a disconnect occurs before `writeCallback` is invoked, in which case `writeCallback` can be assigned to null in Peripheral.java line 344.
Note that many NPEs can happen as a result of a lack of thread safety when accessing the `gatt` object, especially during disconnects.  I've been working on a fix [here](https://github.com/TraFriTCR/react-native-ble-manager/tree/android-thread-safety-enhancements).  Feel free to incorporate this, otherwise I will make some more changes and do more testing before …
> Write callback NPE fix

- README.md
- android/src/main/java/it/innove/BleManager.java
- android/src/main/java/it/innove/LegacyScanManager.java
- android/src/main/java/it/innove/LollipopScanManager.java
- ios/BleManager.m
Needed this field to add some defensive error handling for a few android devices that returns `SCAN_FAILED_ALREADY_STARTED` sometimes.
Ref.
https://developer.android.com/reference/android/bluetooth/le/ScanCallback#SCAN_FAILED_ALREADY_STARTED
I was not sure how to handle the scenarios where an error message was not provided by the OS, so I just returned 0 for those scenarios. It seems like iOS does not provide that much similar information at least from what I could find
https://developer.apple.com/documentation/corebluetooth/cbcentralmanager/1518986-scanforperipherals
> Adds reason field to BleManagerStopScan event for Android

- BleManager.js
- README.md
- android/src/main/java/it/innove/LollipopScanManager.java
- index.d.ts
Hi, among the scan settings introduced by android on M, this repo maps most but lacks `callbackType` [as documented here](https://developer.android.com/reference/android/bluetooth/le/ScanSettings#CALLBACK_TYPE_ALL_MATCHES).
While trying to figure out what is working wrong with BLE scans on android 13 I tried to set this scan setting myself, so I figured I'd add it to the lib in case it helps anyone.
This setting basically enables android to optionally have a "notify once" behavior for each scanned device, sort of like ios `allowDuplicates`. The tradeoff being we might not have full data on a device when it pops. It also supports another mode (notify on match lost) that is rarely useful.
The default mode I left is the one already enabled by default and supported by this library …
> feat (android ble scan) support callbackType scan setting

- README.md
- android/src/main/java/it/innove/BleManager.java
- index.d.ts
- add enums when values are known ahead of time
- fix: ble state is better documented and this commit fixes a few missing cases in android where state update resulting from checkState() might not be the good one (turning_on, turning_off)
- fix: typing errors for readRSSI & requestConnectionPriority
- updated docs
> feat (types) various typing improvements

- android/src/main/java/it/innove/Peripheral.java
See comments on my previous push request here: https://github.com/innoveit/react-native-ble-manager/pull/963
The previous push request used `.forEach`, which is from a more recent version of Java, and isn't compatible with SDK 21. I've updated those lines to used an enhanced for loop instead.
> Fixing minSDK incompatibility caused by .forEach

- README.md
- android/src/main/java/it/innove/LollipopScanManager.java
- src/index.ts
- src/types.ts
- added as a new option in scanOptions to make it backward compatible
> feat (android scan) support scan filter by exact advertising name

- README.md
- android/src/main/java/it/innove/BleManager.java
- ios/BleManager.m
- src/index.ts
- ios: fix deprecated use of CBCentralManager for state mapping
> feat (checkState) checkState method now resolves to the current BLE state

- README.md
- android/src/main/java/it/innove/BleManager.java
- android/src/main/java/it/innove/Peripheral.java
- example/App.tsx
- ios/BleManager.h
- ios/BleManager.m
- ios/CBPeripheral+Extensions.m
- src/index.ts
Implements a new function `readDescriptor` for reading the values of characteristic descriptors.
Discovery on the iOS side had to be extended a bit, as it was not even discovering the descriptors.
To properly implement this on the iOS side this PR also fixes part of the disparity between the returned iOS JS object and the returned Android JS object, by renaming the iOS JS descriptor UUID field from `descriptor` to `uuid`. This commit can be merged as standalone, but #984 should also be merged, as it seems to address the discrepancy between objects more fully.
Resolves #817
> Implement a function for reading descriptors

- ios/BleManager.m
- ios/CBPeripheral+Extensions.m
iOS and android data returned from native to js was quite different. This PR attempts to resolve it by correcting iOS native code
Another behaviour observed was iOS converts uuid to string in upper case which is actually a wrong behaviour as per https://www.itu.int/rec/T-REC-X.667/en
Android handles it correctly.
So to conform to the standard and to maintain uniformity all uuid strings are converted to lowercase.
Since this involves data structure changes, I believe this will become a breaking change for those who are using work arounds based on platform os.
> fix: conform ios native data to match the typescript model

- README.md
Since #866 the implementation for `startNotificationUseBuffer` requires to pass the buffer size in bytes and not the number of messages that the buffer holds. 
The docs were now updated accordingly.
> docs: fix buffer argument explanation for startNotificationUseBuffer

- ios/BleManager.m
I got a report [on my lib ](https://github.com/RonRadtke/react-native-blob-util/issues/253) about a duplicate symbol.
I fixed it on my side, but since it can happen with other libs too I think it would be worth fixing it here too.
> fixing duplicate symbol hasListeners

- ios/BleManager.m
Hi there! I'm currently focused on improving my iOS development skills, and to achieve this, I've been reading and experimenting with some native code. While going through this library, I encountered two typing warnings that I attempted to resolve. I would greatly appreciate it if you could let me know if my solution was the correct approach. Thank you.
Fix: 
- Remove the unused variable `peripheralUUIDString` in the function `didDiscoverCharacteristicsForService`
- Update the prop type of `centralManagerStateToString` from `int` to `CBManagerState`
> fix(BleManager): type warning

- src/types.ts
Native code puts data in map based on service uuids. Probably this property could be also required but I am not 100% sure if it is always empty object if no service data is present.
> Fix serviceData type

- android/src/main/java/it/innove/NotifyBufferContainer.java
From the documentation, I understand that the logic should be this (you can run the code on the website
https://www.jdoodle.com/online-java-compiler/)
```java
import java.nio.ByteBuffer;
public class MyClass {
public static void main(String args[]) {
ByteBuffer items = ByteBuffer.allocate(5);
byte[] init = {0};
byte[] value = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
byte[] toInsert = null;
byte[] rest = null;
// initial values
items.put(init);
if (value.length > items.remaining()) {
int restLength = value.length - items.remaining();
rest = new byte[restLength];
toInsert = new byte[items.remaining()];
System.arraycopy(value, 0, toInsert, 0, toInsert.length);
System.arraycopy(value, toInsert.length, rest, 0, rest.length);
} else {
toInsert = value;
}
System.out.println("toInsert");
for (int i = …
```
> Fix buffer

- ios/BleManager.m
I noticed when setting up handling events in the background that we did not receive the events for updateCharacteristics etc. After some digging it turns out that the delegate for the connected peripherals is not set, and as far as I have found, connecting when the react-native code is running seems to be too late to receive the characteristics update. 
Turns out that setting `peripheral.manager = self` in the `willRestoreState` handler solved the issue, and all events end up in our typescript handlers.
Should resolve #1035
> Set peripheral delegate when restoring state

- README.md
For Apps with an Deployment target of 12.4 (default in RN 0.72) another key is needed in the plist ("NSBluetoothPeripheralUsageDescription").
Adding this to the Readme might be helpful because most devs have to do that.
Source: 
`"If your app has a deployment target earlier than iOS 13, add the NSBluetoothPeripheralUsageDescription key to your app’s Information Property List file in addition to this key."`
https://developer.apple.com/documentation/bundleresources/information_property_list/nsbluetoothalwaysusagedescription#discussion
> improve docs on iOS app with deployment target older than 13.

- android/src/main/java/it/innove/Peripheral.java
[59c37a3](https://github.com/innoveit/react-native-ble-manager/commit/59c37a3084769ea6b7333df30f279ff6bfbde314) inadvertently introduced two recursive loops in the onCharacteristicChanged & onCharacteristicRead methods, affecting devices running Android 13+ (see #1128).
We addressed the problem by adding a conditional check to limit the execution of the overlapping method to Android 12 (API level 31) and below.
> Fix recursive loops causing StackOverflowError on Android 13+

- ios/BleManager.swift
The `if var ... = dict[key]` syntax doesn't return a reference, but a copy which must then be inserted back to the dictionary.
> ios: correctly insert callbacks

- android/build.gradle
Gradle 8.0.2 - Update build.gradle w/ Namespace
FAILURE: Build failed with an exception.
```
* What went wrong:
A problem occurred configuring project ':react-native-ble-manager'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
> Namespace not specified. Please specify a namespace in the module's build.gradle file like so:
android {
namespace 'com.example.namespace'
}
```
> [Android] Update build.gradle

- docs/methods.markdown
The following function name has a type in it in documention:
`getMaximumWriteValueLengthForWitResponse`
> Fix documentation typo

- react-native-ble-manager.podspec
We were running into build errors when trying to use this library, specifically that `CBManagerState` is not available below iOS 10. We ourselves have everything pinned to iOS 13, and the only source of iOS < 10 we could find was this library.
Updating the podspec to reflect the requirement did the trick, so I hope this can be useful to other people as well.
Thanks for considering and thanks for a great library!
> Fixed podspec to require iOS 10 instead of iOS 9, to prevent build errors on iOS

- ios/BleManager.m
The signature of `isScanning` is incorrect in the iOS native code RTC definitions, leading to a runtime exception when calling the function:
This PR fixes the signature, allowing the function to be called successfully on iOS again.
> Fixed incorrect signature for isScanning: on iOS

- android/src/main/java/it/innove/DefaultScanManager.java
- docs/methods.markdown
- src/types.ts
Currently it is not possible to filter by manufacturer id or data during scan on android. This PR adds an optional scan option to filter for peripherals using androids `ScanFilter.Builder.setManufacturerData`.
Not sure whether something similar is possible on iOS, so currently it only works on android.
This shouldn't be a breaking change.
Example usage:
```ts
await BleManager.scan([], 5, false, {
manufacturerData: {
manufacturerId: 0xe4f7,
manufacturerData: [12,3,7],
manufacturerDataMask: [0,0,1]
},
});
```
> feature: scan filter for manufacturer data

- android/src/main/java/it/innove/Peripheral.java
The write callback should not be passed into the callback. Instead there should be no result since an error is already passed.
Relevant ADB logs:
```
02-21 13:25:13.231 31032 31032 E ReactNativeBleManager: java.lang.RuntimeException: Cannot convert argument of type class com.facebook.react.bridge.CallbackImpl
02-21 13:25:13.231 31032 31032 E ReactNativeBleManager: 	at com.facebook.react.bridge.Arguments.fromJavaArgs(Arguments.java:187)
02-21 13:25:13.231 31032 31032 E ReactNativeBleManager: 	at com.facebook.react.bridge.CallbackImpl.invoke(CallbackImpl.java:31)
02-21 13:25:13.231 31032 31032 E ReactNativeBleManager: 	at it.innove.Peripheral$3.run(Peripheral.java:1078)
02-21 13:25:13.231 31032 31032 E ReactNativeBleManager: 	at it.innove.Peripheral$2.run(Peripheral.java:956)
02-21 …
```
> Fix crash during doWrite error handling

- ios/Helper.swift
According to [types.ts](https://github.com/innoveit/react-native-ble-manager/tree/master/src/types.ts) file, retrieveServices command should include 
```
id: string;
rssi: number;
name?: string;
advertising: AdvertisingData; 
```
as response. For Android it works as described, but ios since swift migration returns only characteristics and services. This small fix brings back missing data to the response.
> adjusted retrieveServices response for ios

- android/build.gradle
- android/src/main/java/it/innove/BleManager.java
Since android 13 **were added** two flags when registering receivers: **RECEIVER_EXPORTED** and **RECEIVER_NOT_EXPORTED**. 
Those flags explicitly tells  whether the intention filters are for in-app or for other apps intents too.
I guess RECEIVER_NOT_EXPORTED is the best suitable since we don't want other apps messing up with our intents.
When that flag is not set Android always crashes the app with a exception.
Tested on Android 14.
Solves the #1186.
Android registerReceiver full description: https://developer.android.com/reference/android/content/Context#registerReceiver(android.content.BroadcastReceiver,%20android.content.IntentFilter,%20int)
> Add support for Android 14 (Fix crash issue on Android 14)

- android/src/main/java/it/innove/BleManager.java
- android/src/main/java/it/innove/CompanionScanner.java
- docs/events.markdown
- docs/methods.markdown
- ios/BleManager.m
- ios/BleManager.swift
- src/index.ts
- src/types.ts
Android's `CompanionDeviceManager` is used to get access[1,2] (association) to a Bluetooth LE (and classic Bluetooth) devices without requiring too broad permission set (notably location on older android versions).
Using `CompanionDeviceManager` is also a requirement for implementing background connection management, tho' it also requires the application to implement `CompationDeviceService`[3].
`CompationDeviceManager` availability is not guaranteed, hence the few API version and feature detection checks.
iOS stubs are missing at the moment.
1: https://developer.android.com/develop/connectivity/bluetooth/companion-device-pairing
2: https://developer.android.com/reference/android/companion/CompanionDeviceManager
3: https://developer.android.com/reference/android/companion/CompanionDeviceSe …
> [RFC] Implement companion device manager support

- example/components/ScanDevicesScreen.tsx
- example/package-lock.json
- ios/BleManager.swift
This fixes issue #1233.
Crash is caused by concurrent access of dictionary `readCallbacks[key]` in the if-statement condition.
1. Fixing the issue by wrapping the entire if-statement in serialQueue.sync so that concurrent calls are sequentialized.
2. Add "Read characteristics" button in example app to `console.log` all characteristics for connected peripherals
Applied the patch ([test-concurrency.patch](https://github.com/user-attachments/files/15812595/test-concurrency.patch)) to simulate multiple read events and:
* Verified ios example app crashes before fix.
* Verified ios example app does not crash after fix.
> Fix ios native crash caused by concurrent dictionary access

- ios/Helper.swift
In iOS code, We are building a unique key for a given `peripheral / characteristic / descriptor`, with using `Helper.key` method.
Here we are using `peripheral.uuidAsString` to build the final key but as this is a function and not a value, this will always return instead of the actual uuid string. and so, if we are reading BLE characteristic values for different peripherals, it will always return the same key. And eventually app will be updated with the same readcallbacks every time instead of reporting readcallbacks as per peripheral.
To get the correct string we should be calling `peripheral.uuidAsString()` and so we get a unique key built for each use-case
Understanding by printing values:
```
static func key(forPeripheral peripheral: CBPeripheral,
andCharacteristic characteristic: …
```
> Fixing uuidAsString calls in Helper key method

- android/src/main/AndroidManifest.xml
I need permissions to run on Android14 as react-native-ble-plx.
https://github.com/dotintent/react-native-ble-plx/blob/master/android/src/main/AndroidManifest.xml
Environment that I tried.
ReactNative: 0.71.14
Expo: 48.0.21
Android device: ASUS_AI2202 with Android14
react-native-ble-manager: 11.5.3 and 11.5.5
> Update AndroidManifest.xml to support new options

- ios/BleManager.swift
That bug was a tricky one. I was wondering why I couldn't properly detect iOS errors like `Authentication is insufficient.` or `Encryption is insufficient.` which happen after "forgetting" a BLE device and then trying to read a characteristic. Even when wrapping a `try ... catch` block around a `read()` call, `read()` only returned a null buffer instead of throwing an error.
It took me a while to find the underlying problem which is an NSError occurring in [peripheral(_:didUpdateValueFor:error:)](https://developer.apple.com/documentation/corebluetooth/cbperipheraldelegate/peripheral(_:didupdatevaluefor:error:)-1xyna) directly being passed as argument for `RCTResponseSenderBlock` although it is not a standard JSON type. As a result, on the Javascript-side of React Native the NSError was …
> [FIX] errors were ignored due to broken serialization in read()

- ios/BleManager.swift
- src/types.ts
The event should be sent to the javascript listeners, not broadcasted to the iOS notification center.
Add typescript type for the event.
The event isn't currently working at all, because its send to the wrong place.
> ios: fix willRestoreState event

- ios/BleManager.mm
Fixed an iOS build failure caused by incorrect double to NSNumber conversion
I also tested build and run.
https://github.com/aoiyu/react-native-ble-manager/blob/211062263fdf604a548e1d23a3b6556a4707f21c/ios/BleManager.mm#L217-L217
fixes #1307
Please let me know if you need any additional information or changes.
> ios: Fix incorrect double -> NSNumber conversion

- ios/BleManager.h
- ios/BleManager.swift
Allow to access `getCentralManager` and `getInstance` methods in AppDelegate. Related to [this](https://github.com/innoveit/react-native-ble-manager/issues/664) question. Accessing these methods allows to combine this lib with nordic-dfu, as stated in their [docs](https://github.com/Pilloxa/react-native-nordic-dfu?tab=readme-ov-file#bluetooth-integration)
> feat(v11): Expose getCentralManager and getInstance methods

- README.md
- docs/Gemfile.lock
- docs/events.markdown
- docs/methods.markdown
There's 35 methods, so that ToC starts closed.
Also adds instructions for testing docs locally in the README
Fixes #1332
> docs: add table of contents to events and methods

- android/src/main/java/it/innove/BleManager.java
This is a PR to fix the errors like
```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'void com.facebook.react.bridge.CxxCallbackImpl.invoke(java.lang.Object[])' on a null object reference
at it.innove.NativeBleManagerSpec.emitOnDidUpdateState(NativeBleManagerSpec.java:46)
at it.innove.BleManager$MyBroadcastReceiver.onReceive(BleManager.java:142)
```
```
Fatal Exception: java.lang.RuntimeException: Error receiving broadcast Intent { act=android.bluetooth.adapter.action.STATE_CHANGED flg=0x5000010 (has extras) } in it.innove.BleManager$2@48d9436
at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1708)
at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(:2)
at …
```
> fix: removing event listeners in invalidate

- android/src/main/java/it/innove/BleManager.java
This PR requests to backport PR #1367 into the v11.x branch.
As described in original PR, this protects against the possibility of trying to invoke the callback twice in case of an exception thrown by startActivityForResult, which causes Java exception on Android.
> [backport] Ensure enable bluetooth callback is set to null on exception (#1367)

- docs/install.markdown
Add a quick reference of how the Android permissions should be handled.
> Docs: Add a general react-native way to handle bluetooth Android permissions

- ios/NotifyBufferContainer.swift
- ios/SwiftBleManager.swift
- src/index.ts
This PR adds a similar implementation for `startNotificationWithBuffer()` for iOS as it is for Android right now.
Moreover, it fixes a mismatch in `index.ts` regarding the signature of this method to allow calls from the JS layer.
_Resolves #883_
> [iOS] Feature: start notification with buffer
