innoveit/react-native-ble-manager

- android/src/main/java/it/innove/Peripheral.java
Peripheral.removeNotify() doest not reset the descriptor on android so notification are never stopped on BLE device.
```java
//this call was missing
descriptor.setValue(BluetoothGattDescriptor.DISABLE_NOTIFICATION_VALUE);
```
A new private `setNotify()` method was added to set notify and re/setting descriptor.
This method is now called in `registerNotify()` and `removeNotify()`
```java
private void setNotify(UUID serviceUUID, UUID characteristicUUID, Boolean notify, Callback success, Callback fail)
```
> [ANDROID] fix Peripheral.removeNotify()

- README.md
Adding a simple practical example
> adding basic example

- BleManager.js
Fixes https://github.com/innoveit/react-native-ble-manager/issues/38
> add maxByteSize param to writeWithoutResponse

- android/src/main/java/it/innove/BleManager.java
It will occur a error if it run on a device that has no bluetooth. such as simulator.
> [Android] Fix a issue when a device has no bluetooth

- android/src/main/java/it/innove/BleManager.java
- android/src/main/java/it/innove/Peripheral.java
Hi,
This patch allows to connect to a device which has not been scanned already from Android.
> Ability to connect to a new device that has not been scanned

- README.md
include dependencies for the example, this causes the newbies less hassle and they can setup their first app in seconds.
> enhance example by adding dependencies to it

- android/src/main/java/it/innove/UUIDHelper.java
> fix stackoverflow in UUIDHelper.uuidFromString

- BleManager.js
- android/src/main/java/it/innove/BleManager.java
- android/src/main/java/it/innove/LegacyScanManager.java
- android/src/main/java/it/innove/LollipopScanManager.java
- android/src/main/java/it/innove/ScanManager.java
- ios/BleManager.m
This adds in support using the scan method for optionally specifying ScanSettings.Builder params in android. All are supported as long as the device is supported for that param.  #142
> Support in for optionally customizing ScanSettings 

- README.md
Previously the example code used a 30 second scan duration, however the timer interval was set to 3 seconds. By making both 3 seconds, tapping the button now correctly stops scanning. Thanks!
> fixed example so it stops scanning

- README.md
Modify README to add description about setting Android scan options after 5.0
> Add description for Android scan options

- README.md
Some info about data convert for write and writeWithoutResponse functions.
> Data preparation info in README file.

- README.md
see https://github.com/innoveit/react-native-ble-manager/issues/238
> Improving `read()` example

- README.md
Android minSdkVersion was changed by https://github.com/innoveit/react-native-ble-manager/commit/c9527452acfdf9f926edf2c8e7ffab82bf42f480
> Fix Android minSdkVersion in readme

- ios/BleManager.m
> Fix null updateValue crash on iOS #288

- README.md
multiple call of `start()` causes problems.
https://github.com/innoveit/react-native-ble-manager/issues/243#issuecomment-351352252
> Add a note of caution about multiple start() call in readme

- ios/BleManager.m
Turns out the issue in https://github.com/innoveit/react-native-ble-manager/issues/294 Still happens. You can reproduce it if you start scanning and then reload your React application before the timer runs out. When the timer fires you will get the assert. The timer retains the BleManager which means it doesn't dealloc. The bridge has reloaded and there are two copies of the BleManager. I added an observer to the notification for reloading and now invalidates the scanner and all the peripheral delegates.
I have tested this and it fixes the issue we were having with the crash.
> Fixing issue with scanning and reloading the applicaiton

- BleManager.js
- README.md
- android/src/main/java/it/innove/BleManager.java
- android/src/main/java/it/innove/LollipopScanManager.java
- android/src/main/java/it/innove/Peripheral.java
This addition in functionality closes #231.
> Added functionality to request the connection priority used for a given connection for Android

- android/src/main/java/it/innove/Peripheral.java
Adjusted a bug on Android. Android was hanging on connect and getting connection error never resolving the promise, support versions android M and other versions.
This commit resolves the issues:
android 4.4 fail to connect with error status 133 #193 
https://github.com/innoveit/react-native-ble-manager/issues/193
Android is hanging on connect #270
https://github.com/innoveit/react-native-ble-manager/issues/270
Possible GATT disconnection issue on Samsung devices #252
https://github.com/innoveit/react-native-ble-manager/issues/252
> Adjusted android hanging on connect

- BleManager.js
- README.md
- android/src/main/java/it/innove/BleManager.java
- android/src/main/java/it/innove/Peripheral.java
Useful during development and for those pasky times where for some reason ble-manager doesn't find your custom services
> Add refreshCache method that refreshes service discovery cache

- android/src/main/java/it/innove/Peripheral.java
https://github.com/innoveit/react-native-ble-manager/issues/343
> Android 4.4.4 application crashing during connecting

- ios/BleManager.m
https://github.com/innoveit/react-native-ble-manager/issues/274
> Fix readRSSI callbacks removal to use proper key on iOS

- android/src/main/java/it/innove/Peripheral.java
Removed the connectionStateChange to prevent multiple connect events fixing #386
> Removed connection state change

- android/src/main/java/it/innove/Peripheral.java
Fix issue: https://github.com/innoveit/react-native-ble-manager/issues/376
Reference closed PR: https://github.com/innoveit/react-native-ble-manager/pull/420
> Fix for android advertisement polling

- README.md
- android/src/main/java/it/innove/Peripheral.java
Android only feature
Updated the README
> sending status BleManagerDisconnectPeripheral cb

- index.d.ts
getConnectedPeripherals should return a Promise<any[]> instead of Promise<void>
> Fix typescript definition.

- README.md
fixed a little typo or copy paste error
> fixed typo in refreshCache Method example

- ios/BleManager.m
added [writeQueue removeAllObjects] inside didConnectPeripheral.
> clear queue when connected to peripheral

- README.md
It was necessary to see the example code to properly declare the bleManagerEmitter.
> Shows how to declare the bleManagerEmitter inside BleManagerDidUpdateValueForCharacteristic.

- README.md
- android/src/main/java/it/innove/LollipopScanManager.java
- index.d.ts
Allow configuring the report delay on Android scans
> Set report delay Android scan option

- example/App.js
`PermissionsAndroid.requestPermission` is deprecated
> Use PermissionsAndroid.request in example

- android/src/main/java/it/innove/BleManager.java
I experienced the same issue described in #577 and the fix proposed in the issue does indeed resolve the issue for me.  This pull request contains the fix proposed in the issue.
> Fix #577 - Duplicate characteristic updates

- android/src/main/java/it/innove/Peripheral.java
This probably rates a new npm version.
> Fix #638 - Restore calling of disconnect handlers

- BleManager.js
- android/src/main/java/it/innove/BleManager.java
- added intent and action to pair automatically with ble device
- in createBond passing peripheralUUID and pin will pair with that peripheral automatically
- just passing peripheralUUID will ask for pin (manual action)
> Modified code to allow auto paring

- README.md
- index.d.ts
- ios/BleManager.m
> Updated code in module export createBond function

- index.d.ts
Currently the `PeripheralInfo` type does not seem to cover a lot of the fields that get loaded from `BleManager.retrieveServices`. I am not sure if that is intentional 
Currently it is difficult to use this library with typescript when trying to use attributes that do not have typedefs.
For now I have used a few examples I have used from calling the method on android to infer the typing where possible though this is not exhaustive. Also this was done on android only (not sure if IOS returns different data)
```json
{
"characteristics": [
{
"properties": {
"Read": "Read"
},
"characteristic": "2a00",
"service": "1800"
},
{
"properties": {
"Read": "Read"
},
"characteristic": "2a01",
"service": "1800"
},
{
"properties": {
"Write": "Write",
"Read": "Read"
},
"characteristic": "2a02",
"service": …
```
> Fix: Typings for PeripheralInfo lack a few fields

- README.md
#805
I have tested the permissions on the following android versions:
- 8.1 (27)
- 11 (30)
- 12 (31)
> Update README for Android 12

- android/build.gradle
Fix lambda expressions are not supported in -source 7
> Fix: lambda expressions

- android/src/main/java/it/innove/Peripheral.java
It should fix issues :
https://github.com/innoveit/react-native-ble-manager/issues/900
And finish the fix for : 
https://github.com/innoveit/react-native-ble-manager/issues/885
https://github.com/innoveit/react-native-ble-manager/pull/888
... the issue was still present
> fix dual callback call on connection reset

- android/src/main/java/it/innove/NotifyBufferContainer.java
- android/src/main/java/it/innove/Peripheral.java
- example/package-lock.json
Fixes the build warnings and errors for #998 .
> fix: build errors on buffer container changes

- ios/BleManager.m
> Sync behavior with Android (Support unlimited scan time for iOS)

- android/src/main/java/it/innove/NotifyBufferContainer.java
- android/src/main/java/it/innove/Peripheral.java
The overfill of the notification buffer was not process correctly.
This is a proposed fix.
> Fix notification buffer put method

- ios/BleManager.m
Handling concurrency issue on iOS when callback dictionary is accessed by multiple thread/code.
This fixes the crash on iOS #1082 
In [BleManager.m](https://github.com/innoveit/react-native-ble-manager/blob/master/ios/BleManager.m), the code in insertCallback and invokeAndClearDictionary may be trying to access same dictionary/callback entry at the same time and causing the crash.
Wrapping them in `@synchronize` will add a thread lock to prevent object mutating by different threads at the same time.
> For iOS, fix concurrency issue while accessing callback list

- README.md
- android/src/main/java/it/innove/DefaultScanManager.java
- src/index.ts
- src/types.ts
https://github.com/innoveit/react-native-ble-manager/issues/1090
This feature for Android supports providing multiple string for scanning.
Scanning results should be all devices with name that is included in this array.
> Support multiple device scan

- android/src/main/java/it/innove/DefaultPeripheral.java
- android/src/main/java/it/innove/Peripheral.java
- src/types.ts
This PR contains proposal of solution for #1099.
Unfortunately, i'm not familiar enough and do not have the right software/hardware to modify iOS part of this library.
So if these changes are fine for you, please fell free to add iOS part corresponding to this update.
Please be aware that this can be considered as breaking change, as one of the main interfaces is modified. But in my opinion it is required to change to sort things out.
> Fix manufacturer data

- ios/Helper.swift
Fix https://github.com/innoveit/react-native-ble-manager/issues/1114
> fix ios BLEState backward compatibility issue

- ios/BleManager.swift
- ios/Helper.swift
- src/index.ts
Fix for https://github.com/innoveit/react-native-ble-manager/issues/714
Fix for https://github.com/innoveit/react-native-ble-manager/issues/1140
> Fix ios bugs

- android/src/main/java/it/innove/CompanionScanner.java
Add missing null checks to companion scanner, and make sure that the activity result always ends up calling the scan callback.
Fixes #1276
> bugfix: add missing null checks to CompanionScanner

- ios/BleManager.h
- ios/BleManager.mm
- ios/SwiftBleManager.swift
Same as https://github.com/innoveit/react-native-ble-manager/pull/1317 but for v12
> feat(v12): Expose getCentralManager and getInstance methods

- docs/events.markdown
- docs/index.markdown
- docs/methods.markdown
I noticed some typos, so here are some fixes
> Fix various typos
